DROP DATABASE IF EXISTS MESSENGER;
CREATE DATABASE MESSENGER;

USE MESSENGER;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
id_user INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR (40) NOT NULL,
birthday DATE NOT NULL,
biography VARCHAR (100) NOT NULL,
cep INT (8) NOT NULL,
street VARCHAR (40) NOT NULL,
num INT NOT NULL,
neighborhood VARCHAR (40) NOT NULL,
city VARCHAR (40) NOT NULL,
state CHAR(2) NOT NULL,
phone VARCHAR (15) NOT NULL,

PRIMARY KEY (id_user)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS Message;

CREATE TABLE Message (
id_message INT UNSIGNED NOT NULL AUTO_INCREMENT,
send_user INT UNSIGNED NOT NULL,
message_text TEXT NOT NULL,
send_date DATE NOT NULL,

PRIMARY KEY (id_message),
FOREIGN KEY (send_user) REFERENCES Users(id_user)
)ENGINE=InnoDB;

